order:
  params:
    p1: "order-base"
    p2: 30

spring:
  datasource:
    url: jdbc:h2:mem:order-db

# OpenFeign logs
feign:
  client:
    config:
      default:
        loggerLevel: full

logging:
  level:
    com:
      practice:
        orderservices:
          services:
            rest:
              CustomerRestClientService: debug
              InventoryRestClientService: debug

